FROM python:3.12-slim

WORKDIR /app

COPY ./frontend/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./frontend/streamlit_app.py /app/

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8502"]
