FROM python:3.12-slim

WORKDIR /app

COPY ./frontend/requirements.txt /app/requirements.txt
COPY ./backend/shared/requirements.txt /app/shared_requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir -r /app/shared_requirements.txt

COPY ./frontend /app/frontend
COPY ./backend/shared /app/shared
COPY .env /app/.env

ENV PYTHONPATH=/app

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port", "8502"]