FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY ./backend/fastapi_app/requirements.txt ./requirements.txt
COPY ./shared/requirements.txt ./shared_requirements.txt

RUN pip install --no-cache-dir -r requirements.txt -r shared_requirements.txt

COPY ./backend/fastapi_app ./fastapi_app
COPY ./shared ./shared
COPY .env ./.env

ENV PYTHONPATH=/app:/app/fastapi_app

CMD ["uvicorn", "fastapi_app.main:app", "--host", "0.0.0.0", "--port", "8000"]