FROM python:3.12-slim

WORKDIR /app

COPY ./backend/fastapi_app/requirements.txt /app/requirements.txt
COPY ./backend/shared/requirements.txt /app/shared_requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir -r /app/shared_requirements.txt

COPY ./backend/fastapi_app /app/fastapi_app
COPY ./backend/shared /app/shared

COPY .env /app/.env

ENV PYTHONPATH=/app

CMD ["uvicorn", "fastapi_app.app:app", "--host", "0.0.0.0", "--port", "8000"]
