FROM python:3.12-slim

WORKDIR /app

COPY ./backend/flask_app/requirements.txt /app/requirements.txt
COPY ./backend/shared/requirements.txt /app/shared_requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir -r /app/shared_requirements.txt

COPY ./backend/flask_app /app/flask_app
COPY ./backend/shared /app/shared

ENV FLASK_APP=/app/flask_app/app.py
ENV PYTHONPATH=/app

CMD ["flask", "run", "--host", "0.0.0.0"]
